learn k8s

diff --git a/.github/workflows/example07.yml b/.github/workflows/example07.yml
--- a/.github/workflows/example07.yml
+++ b/.github/workflows/example07.yml
@@ -7,5 +7,6 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - run: |
-          echo "::error Intentional Error ::Missing semicolon"
-          exit 1
+          #echo "::error Intentional Error ::Missing semicolon"
+          #exit 1
+          echo "::Summary 100 resource created ::Missing semicolon"
